config/routes.rb
Rails.application.routes.draw do
  resources :flights, only: [:show, :index]
  resources :bookings, only: [:show, :new, :create]
  root "flights#index", search: {to: "YVR", from: "YVR", passenger_count: "2", date:""}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :flights

  def self.truncated_codes(length)
    all.map { |airport| "#{airport.code}: #{airport.name.truncate length }"}
  end

  def to_s
    code
  end
  
  AIRPORT_LIST = [
      ["Vancouver International Airport","YVR"],
      ["Toronto Pearson International Airport","YYZ"],
      ["Halifax Stanfield International Airport","YHZ"],
      ["Montreal Pierre Elliott Trudeau International Airport","YUL"],
      ["Ottawa McDonald-Cartier International Airport","YOW"],
      ["Calgary International Airport","YYC"],
      ["Winnipeg James Armstrong Richardson International Airport","YWG"],
      ["Victoria International Airport","YYJ"],
      ["St. John’s International Airport","YYT"],
      ["Edmonton International Airport","YEG"],
      ["Montreal Saint-Hubert Airport","YHU"],
      ["Boundary Bay Airport","YDT"],
      ["Quebec City Jean Lesage International Airport","YQB"],
      ["Billy Bishop Toronto City Airport","YTZ"],
      ["Gander International Airport","YQX"],
      ["Greater Moncton Romeo LeBlanc International Airport","YQM"],
      ["Regina International Airport","YQR"],
      ["London International Airport","YXU"]
    ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_and_belongs_to_many :passengers, inverse_of: :booking
  accepts_nested_attributes_for :passengers

  def named_emails
    passengers.map{|p| p.named_email }
  end
end

app/models/booking_passenger.rb
class BookingPassenger < ApplicationRecord
  belongs_to :booking
  belongs_to :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from, class_name: "Airport"
  belongs_to :to, class_name: "Airport"
  has_many :bookings, inverse_of: :flight
  has_many :passengers, through: :bookings
  scope :future_departures_dates, ->{ select("DISTINCT date(departure_time) AS date").where("departure_time > CURRENT_TIMESTAMP").map(&:date)}
  
  def to_s
    "#{from.code} to #{to.code}. " +
    "#{departure_time.strftime("%b %e, %l:%M%P")}-#{arrival_time.strftime("%l:%M%P")}"
  end

  def self.search(search)
    return Flight.all if search.nil? or
    /^[A-Z]{3}/ !~ search[:to] or
    /^[A-Z]{3}/ !~ search[:from] or
    /^[0-9]+$/ !~ search[:passenger_count] or
    not search[:passenger_count].to_i.between?(1,10)

    from_code = search[:from][0..2]
    to_code = search[:to][0..2]

   

    return Flight.none unless Airport.exists?(code: from_code) and
      Airport.exists?(code: to_code)
    a1 = Airport.find_by(code: from_code) 
    a2 = Airport.find_by(code: to_code)
    return self.where(from: a1) if from_code == to_code
    return self.where(from: a1, to: a2) if /^\d{4}-\d{2}-\d{2}$/ !~ search[:date]

    date_time = DateTime.parse search[:date]
    self.where(from: a1, to: a2, departure_time: date_time.all_day)
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_and_belongs_to_many :bookings
  has_many :flights, through: :bookings

  def named_email
    return %("#{name} <#{email}>")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :passengers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    redirect_to render_404 unless Flight.exists?(booking_params[:flight_id])
    @booking = Booking.new
    @flight = Flight.find(booking_params[:flight_id])
    @passenger_count = booking_params[:passenger_count].to_i
    @booking.passengers = Array.new(params[:passenger_count].to_i, Passenger.new)
  end

  def create
     @flight = Flight.find(params_for_create[:flight_id]) or raise("not found") or not_found
     @flight.bookings.build
     @booking = @flight.bookings.last
     params_for_create[:passengers_attributes].each_pair do |i, passenger_info|
        @booking.passengers.build(passenger_info)
     end
     if (@flight.save)
      redirect_to @booking
      BookingMailer.with(booking: @booking).thank_you_email.deliver_later
     end
  end

  def show
    @booking = Booking.includes(:passengers, flight: [:to, :from]).find_by(id: params_for_show[:id]) or not_found
  end

  private

  def not_found
    raise ActionController::RoutingError.new("Not Found")
    render text: "Not Found", status: "404"
  end

  def booking_params
    params.permit(:flight_id, :passenger_count)
  end

  def params_for_create
    params.require(:booking).permit(:flight_id, passengers_attributes:[:name, :email])
  end

  def params_for_show
    params.permit(:id)
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show]

  def index
    @search = search_params.to_h
    @airport_codes = Airport.all.map{|a| ["#{a.code}: #{a.name.truncate(30)}", a.code]}
    @search_dates = Flight.future_departures_dates
    @flights = Flight.search(search_params).includes(:from, :to)
  end

  def show
    @flight = Flight.find(params[:id])
  end

  def book
    passenger_count = params[:passenger_count].to_i
    @flight = Flight.find params[:id]
    @passengers = Array.new(passenger_count, @flight.passengers.build)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:from, :to, :passenger_count, :date, passengers_attributes:[:id, :name, :email])
    end

    def search_params
      params.require(:search).permit(:from, :to, :passenger_count, :date)
    end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show]

  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/new.html.erb
<h2>Booking for <%= @flight.to_s %></h2>

<%= form_for @booking do |f|  %>
<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Email</th>
  </tr>
  <%= f.hidden_field :flight_id, value: @flight.id %>
  <%= f.fields_for :passengers do |p| %>
    <tr><td>Passenger #<%= p.index + 1 %>:</td>
    <td><%= p.text_field :name %></td>
    <td><%= p.email_field :email %></td>
    </tr>
  <% end %>
  </table>
  <tr>
    <div class="actions">
      <%= f.submit %>
    </div>
  </tr>
<% end %>


app/views/bookings/show.html.erb
<h2>Booking for <%= @booking.flight.to_s %></h2>

<table style="text-align:center;width:30%">
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>
  <tr>
  <% @booking.passengers.each do |passenger | %>
    <tr>
      <td><%= passenger.name %></td>
      <td><%= passenger.email %></td>
    </tr>
  <% end %>
</table>

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_results.html.erb
<!-- header -->
<h2>Available Flights - <%=
  "#{@search[:from][0..2]} to #{@search[:to][0..2]}" +
  " for #{pluralize(@search[:passenger_count], "passenger")}"
  %>
  <% unless @search[:date].empty? %>
    <%= "on #{@search[:date]}" %>
  <% end %>
  </h2>

  <% if @flights.count == 0 %>
    </p>Sorry, no flights based on search criteria!</p>
  <% end %>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Book', new_booking_path(flight_id: flight.id,
          passenger_count: @search[:passenger_count]
          ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flights/_search.html.erb
<%= form_tag(flights_path, method: :GET) do %>
  <%= label_tag( "search[from]", "Departing from:") %>
  <%= select_tag("search[from]", options_for_select(@airport_codes) ) %>
  <%= label_tag("search[to]", "Arriving in:") %>
  <%= select_tag("search[to]", options_for_select(@airport_codes)) %>
  <%= label_tag("search[passenger_count]", "Number of passengers:") %>
  <%= number_field_tag("search[passenger_count]", 2, in: 1..10) %>
  <%= label_tag("search[date]", "Departure Date:") %>
  <%= select_tag("search[date]", options_for_select(@search_dates), include_blank: "(Any)", required: false ) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', 'javascript:history.back()' %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>
  <%= render "search" %>
  
  <% unless @search.nil? %>
    <%= render "results"%>
  <% end %>

<br>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @flight %></h2>
<p>Passenger count: <%= @flight.passengers.count %></p>
<p>
  <%= link_to 'Back', 'javascript:history.back()' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/_form.html.erb
<%= form_with(model: passenger, local: true) do |form| %>
  <% if passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

app/views/passengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passengers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Passport</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.name %></td>
        <td><%= passenger.email %></td>
        <td><%= passenger.age %></td>
        <td><%= passenger.passport %></td>
        <td><%= link_to 'Show', passenger %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger', new_passenger_path %>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Back', passengers_path %>

app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @passenger.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @passenger.age %>
</p>

<p>
  <strong>Passport:</strong>
  <%= @passenger.passport %>
</p>

<%= link_to 'Edit', edit_passenger_path(@passenger) %> |
<%= link_to 'Back', passengers_path %>